import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Strapi Demo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className='py-5 px-4 bg-slate-800'>
        <h1 className='text-2xl text-purple-500 capitalize cursor-pointer'>strapi demo</h1>
      </header>
        {children}
      <footer className='fixed bottom-0 w-full'>
        <p className='text-base text-center'>copyright&copy;2023 all rights reserved</p>
      </footer>
        </body>
    </html>
  )
}
