import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Strapi Demo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className='py-5 px-4 bg-slate-800 flex justify-between sticky z-10 top-0 w-full'>
        <h1 className='text-2xl text-purple-500 capitalize cursor-pointer'><Link href="/" title='Cms Demo'>cms demo</Link></h1>
      <nav>
      <ul className='flex gap-x-4'>
            <li><Link href="strapi" title='Strapi' className='capitalize underline lg:hover:text-purple-500 text-white lg:hover:no-underline'>strapi</Link></li>
            <li><Link href="directus" title='Directus' className='capitalize underline lg:hover:text-purple-500 text-white lg:hover:no-underline'>Directus</Link></li>
          </ul>

      </nav>
      </header>
        {children}
      <footer className='fixed bottom-0 w-full bg-slate-800'>
        <p className='text-base text-center text-purple-500'>copyright&copy;2023 all rights reserved</p>
      </footer>
        </body>
    </html>
  )
}
